name: sneakerstore_client
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  dropdown_button2: ^2.3.9
  get: ^4.6.6
  otp_text_field_v2: ^1.0.3
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  get_storage: ^2.1.1

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.9.2
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

